apiVersion: apps/v1
kind: Deployment
metadata:
  name: kn2359-text-embedding-server-large
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kn2359-text-embedding-server-large
  template:
    metadata:
      labels:
        app: kn2359-text-embedding-server-large
    spec:
      containers:
      - name: kn2359-text-embedding-server-large
        image: /cloudml-project:fall2023
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 50051
        - containerPort: 50052
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/crg9968-service-account.json
        - name: INSTRUCTOR_MODEL_TYPE
          value: "hkunlp/instructor-large"
        volumeMounts:
        - name: google-credentials-volume
          mountPath: /var/secrets/google
          readOnly: true
      volumes:
      - name: google-credentials-volume
        secret:
          secretName: google-credentials