apiVersion: apps/v1
kind: Deployment
metadata:
  name: crg9968-text-embedding-server-base
spec:
  replicas: 0
  selector:
    matchLabels:
      app: crg9968-text-embedding-server-base
  template:
    metadata:
      labels:
        app: crg9968-text-embedding-server-base
    spec:
      containers:
      - name: crg9968-text-embedding-server-base
        image: chanukya43/cloudml-project:fall2023
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 50051
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/crg9968-service-account.json
        - name: INSTRUCTOR_MODEL_TYPE
          value: "hkunlp/instructor-base"
        volumeMounts:
        - name: google-credentials-volume
          mountPath: /var/secrets/google
          readOnly: true
      volumes:
      - name: google-credentials-volume
        secret:
          secretName: google-credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crg9968-text-embedding-server-large
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crg9968-text-embedding-server-large
  template:
    metadata:
      labels:
        app: crg9968-text-embedding-server-large
    spec:
      containers:
      - name: crg9968-text-embedding-server-large
        image: chanukya43/cloudml-project:fall2023
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 50051
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/crg9968-service-account.json
        - name: INSTRUCTOR_MODEL_TYPE
          value: "hkunlp/instructor-large"
        volumeMounts:
        - name: google-credentials-volume
          mountPath: /var/secrets/google
          readOnly: true
      volumes:
      - name: google-credentials-volume
        secret:
          secretName: google-credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crg9968-text-embedding-server-xl
spec:
  replicas: 0
  selector:
    matchLabels:
      app: crg9968-text-embedding-server-xl
  template:
    metadata:
      labels:
        app: crg9968-text-embedding-server-xl
    spec:
      containers:
      - name: crg9968-text-embedding-server-xl
        image: chanukya43/cloudml-project:fall2023
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 50051
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/crg9968-service-account.json
        - name: INSTRUCTOR_MODEL_TYPE
          value: "hkunlp/instructor-xl"
        volumeMounts:
        - name: google-credentials-volume
          mountPath: /var/secrets/google
          readOnly: true
      volumes:
      - name: google-credentials-volume
        secret:
          secretName: google-credentials
