apiVersion: apps/v1
kind: Deployment
metadata:
  name: crg9968-text-embedding-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crg9968-text-embedding-server
  template:
    metadata:
      labels:
        app: crg9968-text-embedding-server
    spec:
      containers:
      - name: crg9968-text-embedding-server
        image: chanukya43/cloudml-project:fall2023
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/crg9968-service-account.json
        volumeMounts:
        - name: google-credentials-volume
          mountPath: /var/secrets/google
          readOnly: true
      volumes:
      - name: google-credentials-volume
        secret:
          secretName: google-credentials
