apiVersion: v1
kind: Service
metadata:
  name: crg9968-text-embedding-server-service-base
  labels:
    app: base-app
    job: base-job
spec:
  selector:
    app: crg9968-text-embedding-server-base
  ports:
    - protocol: TCP
      port: 80
      name: port1
      targetPort: 50051
    - protocol: TCP
      name: metrics
      port: 9090
      targetPort: 50052
  type: LoadBalancer  # use LoadBalancer for external access
---
apiVersion: v1
kind: Service
metadata:
  name: crg9968-text-embedding-server-service-large
  labels:
    app: large-app
    job: large-job
spec:
  selector:
    app: crg9968-text-embedding-server-large
  ports:
    - protocol: TCP
      port: 80
      name: port1
      targetPort: 50051
    - protocol: TCP
      name: metrics
      port: 9090
      targetPort: 50052
  type: LoadBalancer  # use LoadBalancer for external access
---
apiVersion: v1
kind: Service
metadata:
  name: crg9968-text-embedding-server-service-xl
  labels:
    app: xl-app
    job: xl-job
spec:
  selector:
    app: crg9968-text-embedding-server-xl
  ports:
    - protocol: TCP
      port: 80
      name: port1
      targetPort: 50051
    - protocol: TCP
      name: metrics
      port: 9090
      targetPort: 50052
  type: LoadBalancer  # use LoadBalancer for external access
---
apiVersion: v1
kind: Service
metadata:
  name: crg9968-text-embedding-server-service-base-cpu
  labels:
    app: base-app-cpu
    job: base-job-cpu
spec:
  selector:
    app: crg9968-text-embedding-server-base-cpu
  ports:
    - protocol: TCP
      port: 80
      name: port1
      targetPort: 50051
    - protocol: TCP
      name: metrics
      port: 9090
      targetPort: 50052
  type: LoadBalancer  # use LoadBalancer for external access
---
apiVersion: v1
kind: Service
metadata:
  name: crg9968-text-embedding-server-service-large-cpu
  labels:
    app: large-app-cpu
    job: large-job-cpu
spec:
  selector:
    app: crg9968-text-embedding-server-large-cpu
  ports:
    - protocol: TCP
      port: 80
      name: port1
      targetPort: 50051
    - protocol: TCP
      name: metrics
      port: 9090
      targetPort: 50052
  type: LoadBalancer  # use LoadBalancer for external access
---
apiVersion: v1
kind: Service
metadata:
  name: crg9968-text-embedding-server-service-xl-cpu
  labels:
    app: xl-app-cpu
    job: xl-job-cpu
spec:
  selector:
    app: crg9968-text-embedding-server-xl-cpu
  ports:
    - protocol: TCP
      port: 80
      name: port1
      targetPort: 50051
    - protocol: TCP
      name: metrics
      port: 9090
      targetPort: 50052
  type: LoadBalancer  # use LoadBalancer for external access
---
apiVersion: v1
kind: Service
metadata:
  name: crg9968-text-embedding-server-service-large-llm
spec:
  selector:
    app: crg9968-text-embedding-server-large-llm
  ports:
    - protocol: TCP
      port: 80
      name: port1
      targetPort: 50051
    - protocol: TCP
      name: metrics
      port: 9090
      targetPort: 50052
  type: LoadBalancer  # use LoadBalancer for external access
