apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: base-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
      port: metrics
      path: /metrics
  selector:
    matchLabels:
      app: base-app
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: large-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
      port: metrics
      path: /metrics
  selector:
    matchLabels:
      app: large-app
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xl-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
      port: metrics
      path: /metrics
  selector:
    matchLabels:
      app: xl-app
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: base-cpu-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
      port: metrics
      path: /metrics
  selector:
    matchLabels:
      app: base-app-cpu
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: large-cpu-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
      port: metrics
      path: /metrics
  selector:
    matchLabels:
      app: large-app-cpu
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xl-cpu-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
      port: metrics
      path: /metrics
  selector:
    matchLabels:
      app: xl-app-cpu
