apiVersion: v1
kind: Service
metadata:
  name: kn2359-text-embedding-server-service-large
spec:
  selector:
    app: kn2359-text-embedding-server-large
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50051
    - protocol: TCP
      port: 9090
      targetPort: 50052
  type: LoadBalancer  # use LoadBalancer for external access