apiVersion: v1
kind: Service
metadata:
  name: text-embedding-server-service
spec:
  selector:
    app: text-embedding-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50051
  type: LoadBalancer  # use LoadBalancer for external access
